@startuml

left to right direction

rectangle SistemaDeAsistencias{

  actor Profesor
  
  usecase "Exportar informe" as UC9
  usecase "Cambios de grupos" as UC8
  usecase "Baja de grupos" as UC7  
  usecase "Alta de grupos" as UC6
  usecase "Cambios de alumnos" as UC5
  usecase "Baja de alumnos" as UC4
  usecase "Alta de alumnos" as UC3
  usecase "Registro de asistencia" as UC2
  usecase "Lectura de NFC" as UC1 
}

Profesor --> UC2
Profesor --> UC3
Profesor --> UC4
Profesor --> UC5
Profesor --> UC6
Profesor --> UC7
Profesor --> UC8
Profesor --> UC9

UC2 ..> UC1 : <<include>>

@enduml
