@startuml

alt Lectura Correcta

    Usuario -> App: Selecionar Leer NFC
    App --> Usuario: Solicitar NFC
    Usuario -> App: Pasar tarjeta con NFC
    App -> DataSource: Recibir NFC
    DataSource -> DAO: Validar NFC
    DAO -> DataStorage: Verificar NFC
    DataStorage --> DAO: Verificado
    DAO --> DataSource: Validado
    DataSource --> App: Lectura Correcta
    App --> Usuario: Exito

else NFC erroneo

    Usuario -> App: Selecionar Leer NF
    App -> DataSource: Recibir NFC
    DataSource -> DAO: Validar NFC
    DAO -> DataStorage: Verificar NFC
    DataStorage --> DAO: NFC no encontrado
    DAO --> App: Error NFC
    App --> Usuario: NFC invalido

else Lector no funcional

    Usuario -> App: Selecionar Leer NFC
    App -> DataSource: Recibir NFC
    DataSource -> DAO: Error de Lectura
    DAO --> App: Mostrar Error 
    App --> Usuario: Error en Lector NFC 
end

@enduml
