@startuml

class Tarjeta{ 

    Id_NFC String
    TipoLectura enum

}


+class Alumno{

    Numero_Matricula String
    Nombre String
    Grupo grupo 
} 

+class Profesor{

    Id_Profesor String
    Nombre String
    Grupo grupo
    Informe informe

}

+class Grupo{

    Id_Grupo String 
    Alumno alumno
    Profesor profesor

}


-class Informe{

    Profesor profesor 
    Grupo grupo 

}

'Relaciones.

    Alumno }--{ Grupo
    Profesor --|{ Grupo
    Alumno }--{ Profesor
    Profesor --|{ Informe
    Alumno --|| Tarjeta
    Grupo --|{ Informe
 
@enduml
