@startuml

alt Lectura Correcta

    App -> View: Acercar NFC
    View -> Controller: Leer NFC
    Controller -> DataStorage: Recibe NFC
    DataStorage -> DAO: Enivar NFC
    DAO -> B.D: Verificar NFC
    B.D --> DAO: Validado
    DAO --> DataStorage: Enviar respuesta
    DataStorage --> Controller: Exito
    Controller --> View: Lectura exitosa
    View --> App: Reiniciar proceso

else NFC erroneo

    App -> View: Acercar NFC
    View -> Controller: Leer NFC
    Controller -> DataStorage: Recibe NFC
    DataStorage -> DAO: Enivar NFC
    DAO -> B.D: Verificar NFC
    B.D --> DAO: Error de busqueda
    DAO --> DataStorage: Enviar respuesta
    DataStorage --> Controller: Error
    Controller --> View: NFC no valido
    View --> App: Reiniciar proceso

else Lector no funcional

    App -> View: Acercar NFC
    View -> Controller: Leer NFC
    Controller -> DataStorage: Error en Lector
    DataStorage --> Controller: Error
    Controller --> View: Lector no disponible
    View --> App: Fin de proceso

end

@enduml
