@startuml

Usuario -> LectorNFC: getService(Lector)
activate LectorNFC
LectorNFC -> DataSoruce: getService(Lector)
activate DataSoruce
DataSoruce --> LectorNFC: null
deactivate DataSoruce
LectorNFC -> DAO: initialization
activate DAO
DAO -> DataStorage: initialization
deactivate DAO
activate DataStorage
DataStorage--> LectorNFC: Lector object
deactivate DataStorage
LectorNFC --> Usuario: Lector object
deactivate LectorNFC

Usuario -> LectorNFC: getService(Lector)
activate LectorNFC
LectorNFC -> DAO: getService(Lector)
activate DAO
DAO --> LectorNFC: Lector object
deactivate DAO
LectorNFC --> Usuario: Lector object
deactivate LectorNFC

@enduml
