@startuml

App -> Controller: initialization
activate Controller
Controller -> Lector: getService(Lector)
activate Lector
Lector -> S.O. : getService(Lector)
activate S.O.
S.O. --> Lector: null
deactivate S.O.
Lector --> Controller: Lector object
deactivate Lector
Controller --> App: Lector Object
deactivate Controller

App -> Controller: initialization
activate Controller
Controller -> Lector: getService(Lector)
activate Lector
Lector -> S.O.: getService(Lector)
activate S.O.
S.O. --> Lector: Lector object
deactivate S.O.
Lector --> Controller: Lector object
deactivate Lector
Controller --> App: Lector Object
deactivate Controller

@enduml
