@startuml

== Altas Alumnos ==

alt Registro de alumno

    Usuario -> App: Seleccionar alta
    App --> Usuario: Solicitar datos
    Usuario -> App: Ingresar datos
    App -> DataSource: Sensor
    DataSource -> DAO: Insertar 
    DAO --> DataStorage: Guardar
    DataStorage --> DAO: Guardado exitoso
    DAO --> DataSource: Confirmar
    DataSource --> App: Datos guardados
    App --> Usuario: Fin de proceso

else Alumno ya registrado en sistema

    Usuario -> App: Seleccionar alta
    App --> Usuario: Solicitar datos
    Usuario -> App: Ingresar datos
    App -> DataSource: Sensor
    DataSource -> DAO: Insertar 
    DAO --> DataStorage: Guardar
    DataStorage --> DAO: Alumno ya registrado
    DAO --> DataSource: Advertencia
    DataSource --> App: Mostrar Advertencia
    App --> Usuario: Reiniciar proceso

end

== Bajas Alumnos ==

alt Baja de alumno exitoso

    Usuario -> App: Seleccionar baja
    App --> Usuario: Solicitar datos
    Usuario -> App: Ingresar datos
    App -> DataSource: Sensor
    DataSource -> DAO: Validar
    DAO --> DataStorage: Verficar Datos
    DataStorage --> DAO: Encontrado y Eliminado
    DAO --> DataSource: Exito al eliminar
    DataSource --> App: Eliminado
    App --> Usuario: Fin de proceso

else Alumno no encontrado

    Usuario -> App: Seleccionar baja
    App --> Usuario: Solicitar datos
    Usuario -> App: Ingresar datos
    App -> DataSource: Sensor
    DataSource -> DAO: Validar
    DAO --> DataStorage: Verfica Datos
    DataStorage --> DAO: Error de busqueda
    DAO --> DataSource: Alumno no encontrado
    DataSource --> App: Enviar error
    App --> Usuario: Reiniciar proceso


end

== Cambios Alumnos ==

alt Cambio de datos exitoso

    Usuario -> App: Seleccionar Cambios
    App --> Usuario: Solicitar datos
    Usuario -> App: Ingresar datos
    App -> DataSource: Sensor
    DataSource -> DAO: Sobreescribir datos
    DAO --> DataStorage: Cuardar
    DataStorage --> DAO: Guardado exitoso
    DAO --> DataSource: Exito al sobreescribir
    DataSource --> App: Datos guardados
    App --> Usuario: Fin de proceso

else Alumno no encontrado

    Usuario -> App: Seleccionar Cambios
    App --> Usuario: Solicitar datos
    Usuario -> App: Ingresar datos
    App -> DataSource: Sensor
    DataSource -> DAO: Sobreescribir datos 
    DAO --> DataStorage:Guardar
    DataStorage --> DAO: Error de Busqueda
    DAO --> DataSource: Alumno no encontrado  
    DataSource --> App: Datos erroneos
    App --> Usuario: Reiniciar proceso

else Datos repetidos

    Usuario -> App: Seleccionar Cambios
    App --> Usuario: Solicitar datos
    Usuario -> App: Ingresar datos
    App -> DataSource: Sensor
    DataSource -> DAO: Sobreescribir datos
    DAO --> DataStorage: Cuardar
    DataStorage --> DAO: Datos repetidos
    DAO --> DataSource: Error al guardar
    DataSource --> App: Datos nos disponibles
    App --> Usuario: Reiniciar proceso

end

@enduml
