@startuml

== Altas Alumnos ==

alt Registro de alumno

    App -> View: Seleccionar alta
    View -> Controller: Enviar solicitud
    Controller --> View: Solicitar datos
    View -> Controller: Recibir datos
    Controller -> DataStorage: Enviar datos
    DataStorage -> DAO: Insertar
    DAO -> B.D: Guardar
    B.D --> DAO: Guardado Exitoso
    DAO --> DataStorage: Enviar respuesta
    DataStorage --> Controller: Exito
    Controller --> View: Registro exitoso
    View --> App: Fin de proceso
    

else Alumno ya registrado en sistema

    App -> View: Seleccionar alta
    View -> Controller: Enviar solicitud
    Controller --> View: Solicitar datos
    View -> Controller: Recibir datos
    Controller -> DataStorage: Enviar datos
    DataStorage -> DAO: Insertar
    DAO -> B.D: Guardar
    B.D --> DAO: Error de registro
    DAO --> DataStorage: Enviar respuesta
    DataStorage --> Controller: Error
    Controller --> View: Alumno ya registrado en B.D
    View --> App: Reiniciar proceso

end

== Bajas Alumnos ==

alt Baja de alumno exitoso

    App -> View: Seleccionar baja
    View -> Controller: Enviar solicitud
    Controller --> View: Solicitar datos
    View -> Controller: Recibir datos
    Controller -> DataStorage: Enviar datos
    DataStorage -> DAO: Verificar datos
    DAO -> B.D: Validar datos
    B.D --> DAO: Alumno eliminado
    DAO --> DataStorage: Enviar respuesta
    DataStorage --> Controller: Exito
    Controller --> View: Eliminación exitoso
    View --> App: Fin de proceso
    
else Alumno no encontrado

    App -> View: Seleccionar baja
    View -> Controller: Enviar solicitud
    Controller --> View: Solicitar datos
    View -> Controller: Recibir datos
    Controller -> DataStorage: Enviar datos
    DataStorage -> DAO: Verificar datos
    DAO -> B.D: Validar datos
    B.D --> DAO: Error de busqueda
    DAO --> DataStorage: Enviar respuesta
    DataStorage --> Controller: Enviar error
    Controller --> View: Alumno no encontrado
    View --> App: Reiniciar proceso
    
end

== Cambios Alumnos ==

alt Cambio de datos exitoso

    App -> View: Seleccionar cambio
    View -> Controller: Enviar solicitud
    Controller --> View: Solicitar datos
    View -> Controller: Recibir datos
    Controller -> DataStorage: Enviar datos
    DataStorage -> DAO: Insertar
    DAO -> B.D: Sobreescribir
    B.D --> DAO: Guardado exitoso
    DAO --> DataStorage: Enviar respuesta
    DataStorage --> Controller: Exito
    Controller --> View: Cambio exitoso
    View --> App: Fin de proceso

else Alumno no encontrado

    App -> View: Seleccionar cambio
    View -> Controller: Enviar solicitud
    Controller --> View: Solicitar datos
    View -> Controller: Recibir datos
    Controller -> DataStorage: Enviar datos
    DataStorage -> DAO: Insertar
    DAO -> B.D: Sobreescribir
    B.D --> DAO: Error de busqueda
    DAO --> DataStorage: Enviar respuesta
    DataStorage --> Controller: Error
    Controller --> View: Alumno no encontrado
    View --> App: Reiniciar proceso

else Datos repetidos

    App -> View: Seleccionar cambio
    View -> Controller: Enviar solicitud
    Controller --> View: Solicitar datos
    View -> Controller: Recibir datos
    Controller -> DataStorage: Enviar datos
    DataStorage -> DAO: Insertar
    DAO -> B.D: Sobreescribir
    B.D --> DAO: Error al guardar
    DAO --> DataStorage: Enviar respuesta
    DataStorage --> Controller: Error
    Controller --> View: Alumno con datos iguales
    View --> App: Reiniciar proceso

end

@enduml
