@startuml
'Este archivo contiene en texto plano el código necesario para generar el diagrama de clases del sistema.


'Modificaciones: Se incluyó a libnfc dentro del diagrama.

'Un módulo para raspberry pi tiene estos tres modos. Los tomaremos como referencia.
enum TipoDeLectura{

LECTOR
P2P
EMULACION_DE_TARJETA

}

enum Temporalidad{
DIA
SEMANAL
MENSUAL
SEMESTRAL
}

enum Formato{
CSV
XLS
XLSX
PDF

}

enum DatosAlumnoParaReporte{

GRUPO
PERIODO_CURSADO
MATERIA_CURSADA
NUM_ASISTENCIAS
NUM_FALTAS
CALIFICACION

}

interface ILectorTarjeta{

TipoDeLectura TipoActual

}

interface ITarjeta{

long idNFC

}

'Dado que libnfc es una biblioteca ya existente, el paquete es el mejor elemento que se le ajusta.
'Para efectos prácticos basta con dejar solo el nombre de la biblioteca.
package libnfc <<folder>>{


}

'Esta clase técnicamente es protegida porque solo ciertas clases pueden acceder a ella, no todas las clases deben accederla.
class Tarjeta{ 

ITarjeta Tarjeta


}

#class DataStorage{

'Toda esta clase es únicamente de métodos.
read() : Alumno
read() : Informe
write(Alumno)
write(Informe)

}



+class LectorTarjeta{

tipoDeLectura tipoActual

'Métodos.
LeerNFCTarjeta()

}

+class Persona{

String nombre

}

+class Alumno{

DatosAlumnoParaReporte datos
int numeroMatricula
String eMail
Tarjeta tarjetaAsociada
Grupo Grupos[]

'Métodos.


} 

+class Profesor{

int numGruposAsociados
int claveProfesor

'Métodos.
AltaAlumno(Alumno)
BajaAlumno()
CambioAlumno(Alumno)
AltaGrupo(Grupo)
BajaGrupo()
CambioGrupo(Grupo)

}

+class Grupo{

Alumno Alumnos[]
int idGrupo

}

class SistemaAsistencias{

Alumno[] alumnos
Grupo[] grupos

'Métodos.
AccederAInforme()
RegistrarAsistenciaAlumno()
GenerarInformePorTiempo(Temporalidad)
ExportarInforme(Formato)

}

'Privado porque solo el profesor interactúa con él.
-class Informe{

Alumno[] alumnos
Grupo[] grupos


}

'Relaciones.
TipoDeLectura <-- ILectorTarjeta

Tarjeta ..|> ITarjeta
LectorTarjeta <|.. ILectorTarjeta


'Para este sistema un alumno solo puede tener una tarjeta a menos que deba hacer el reemplazo.
Alumno -- Tarjeta: 1

Alumno - DatosAlumnoParaReporte

Tarjeta -- LectorTarjeta

Profesor --|> Persona
Alumno --|> Persona

'Un cambio en la clase grupo afecta a la clase reporte, por eso es una dependencia.
Grupo <.. Informe

Alumno --o Grupo: 1 .. *

libnfc <. LectorTarjeta

SistemaAsistencias ---> Temporalidad
SistemaAsistencias ---> Formato

SistemaAsistencias .> Alumno
SistemaAsistencias .> Grupo
SistemaAsistencias -- Informe

Informe - DataStorage
Informe - Alumno
@enduml
